# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile
tasks:
  - name: Setup all dependenies
    init: |
      export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
      pnpm add -g @project-serum/anchor-cli@0.18.0
      solana config set --url localhost
      pnpm add -g mocha
      pnpm i
