# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile
tasks:
  - name: Setup all dependenies
    init: |
      solana config set --url localhost
      pnpm add -g mocha
      pnpm add -g @project-serum/anchor-cli
      pnpm i
