# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile
tasks:
  - name: Setup all dependenies
    init: |
      export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
      cargo install --git https://github.com/project-serum/anchor --tag v0.18.0 anchor-cli --locked
      solana config set --url localhost
      npm add -g typescript
      npm add -g mocha
      npm add -g ts-mocha
      pnpm i
      cd contract && npm i
      