# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image: fulayfel/gitpod-solana-anchor:latest
tasks:
  - name: Setup all dependenies
    init: |
      export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
      solana config set --url localhost
      pnpm add -g mocha
      pnpm i
