# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile
tasks:
  - init: pnpm add -g mocha
  - init: pnpm i
  - init: solana config set --url localhost
  - init: pnpm add -g @project-serum/anchor-cli
